[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = [
  "npm install -g pnpm@9",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "pnpm build"
]

[start]
cmd = "npx prisma migrate deploy && node dist/main"
